### ISSUE TITLE
Не запускається

### ISSUE THREAD

**Issue by OlehRA** [FaineSwitcher/keyswitcher#4]
На жаль, програма відразу після запуску зачиняється, не видає жодної помилки. Win10 x64, актуальна версія. Установщик Faine Switcher V2 скачаний із веб-сайту. Перевстановлював, не допомогло. З'являється значок в системному лотку і відразу зникає. Також процесу у пам'яті немає. Програма повністю закривається. 
На іншому компі працює без проблем. Підкажіть, де копати

**Comment by RomaRudyak** [comment]
Спройте переглянути логи у папці `%APPDATA%` можна знайти логи.
Також спробуйте запустити програму з під адміна, є ймовірнітсть, що програма немає прав писати файли у папку.

**Comment by OlehRA** [comment]
Проблема вирішилась сама по собі, коли оновився до Win11. Тому причина незапуску залишиться невідомою. Тему закриваю :) Авторам велика подяка
